- frontend/Idle/package-lock.json
- frontend/Idle/src/components/common/BlueButton.jsx
- frontend/Idle/src/components/common/Button.jsx
- frontend/Idle/src/components/common/WhiteButton.jsx
- frontend/Idle/styles/GlobalStyle.jsx
> [FE] 일반 버튼 컴포넌트 구현

- frontend/Idle/src/components/common/Test.jsx
- frontend/Idle/src/components/common/TrimTooltip.jsx
- 폴리곤 + div인지, 하나의 이미지 인지 확인불가.
- 디자이너 답변오면 이어서 작업 예정
> [FE] 툴팁 공용 컴포넌트 구현

- backend/.idea/workspace.xml
- backend/src/main/java/com/autoever/idle/TestController.java
> [test] API Test

- frontend/Idle/src/components/findTrim/FindTrimContent.jsx
- frontend/Idle/src/components/layout/footer.jsx
- frontend/Idle/src/components/layout/header.jsx
- frontend/Idle/src/components/layout/layout.jsx
- frontend/Idle/src/pages/trimPage.jsx
- frontend/Idle/src/styles/GlobalStyle.jsx
> [feat] 트림찾기 모달 위치 수정

- frontend/Idle/src/components/common/WarningModal.jsx
- close #20
location.replace메소드를 이용하여 히스토리가 안남도록(이전페이지 버튼이동이 안되도록) 하였습니다.
> [FE] 경고 모달 컴포넌트 구현

- frontend/Idle/src/components/findTrim/FindTrimContentMain.jsx
- frontend/Idle/src/components/findTrim/TrimBox.jsx
- frontend/Idle/src/components/findTrim/TrimBoxOptionStatus.jsx
- #50
- 기본옵션인지 추가옵션인지 props에 따라 설정
- TrimContainer를 만들어서 정렬 이쁘게
TrimContainer를 만들어서 map함수를 돌렸습니다.
> [FE] 내게 맞는 트림 찾기 커스텀 트림박스 

- backend/src/main/java/com/autoever/idle/domain/bodyType/BodyType.java
- backend/src/main/java/com/autoever/idle/domain/carMaster/CarMaster.java
- backend/src/main/java/com/autoever/idle/domain/carType/CarType.java
- backend/src/main/java/com/autoever/idle/domain/drivingMethod/DrivingMethod.java
- backend/src/main/java/com/autoever/idle/domain/engine/Engine.java
- backend/src/main/java/com/autoever/idle/domain/exteriorColor/ExteriorColor.java
- backend/src/main/java/com/autoever/idle/domain/interiorColor/InteriorColor.java
- backend/src/main/java/com/autoever/idle/domain/option/additionalOption/AdditionalOption.java
- backend/src/main/java/com/autoever/idle/domain/option/defaultOption/DefaultOption.java
- backend/src/main/java/com/autoever/idle/domain/trim/Trim.java
- close #74 
- 스프링 부트 프로젝트 도메인 패키기 초기 세팅
> [BE] 스프링 부트 패키지 구조 설계

- .github/workflows/idle_workflow.yml
- backend/Dockerfile
close #79 
- 무슨 이유로 어떻게 코드를 변경했는지
- 어떤 부분에 리뷰어가 집중해야 하는지
- 개발하면서 어떤 점이 궁금했는지
> [BE] Github Actions 및 Dockefile 수정

- frontend/Idle/src/components/common/OptionModal.jsx
- frontend/Idle/src/components/findTrim/FindTrimContent.jsx
- frontend/Idle/src/components/findTrim/FindTrimContentMain.jsx
- frontend/Idle/src/components/findTrim/OptionBox.jsx
> [Fe] 상세 옵션 정보 모달창 컴포넌트

- .github/workflows/idle_workflow.yml
- backend/.idea/workspace.xml
- backend/Dockerfile
> [BE] Jacaca Report CI 기능 추가 및 Dockerfile 수정

- frontend/Idle/src/components/common/modals/RemoveOptionModal.jsx
- frontend/Idle/src/components/navbar/NavbarBox.jsx
- frontend/Idle/src/pages/billPage.jsx
- frontend/Idle/src/utils/globalCar.jsx
> [FE] navbar, ROmodal 버그 수정

- backend/src/main/java/com/autoever/idle/domain/exteriorColor/ExteriorColorController.java
- backend/src/main/java/com/autoever/idle/domain/exteriorColor/ExteriorColorRepository.java
- backend/src/main/java/com/autoever/idle/domain/exteriorColor/ExteriorColorRepositoryImpl.java
- backend/src/main/java/com/autoever/idle/domain/exteriorColor/ExteriorColorService.java
- backend/src/main/java/com/autoever/idle/domain/exteriorColor/dto/CarExteriorImgDto.java
- backend/src/main/java/com/autoever/idle/domain/exteriorColor/dto/ExteriorColorDto.java
- backend/src/main/java/com/autoever/idle/domain/exteriorColor/dto/ExteriorColorResDto.java
- backend/src/test/java/com/autoever/idle/domain/exteriorColor/ExteriorColorControllerTest.java
- backend/src/test/java/com/autoever/idle/domain/exteriorColor/ExteriorColorRepositoryTest.java
> [BE] 외장 색상 선택 API 구현

- .github/workflows/idle_workflow.yml
> [BE] CI, CD workflow 코드 merge

- frontend/Idle/src/components/BillMain/BillOptionBox.jsx
- frontend/Idle/src/components/BillMain/BillOptionContainer.jsx
- frontend/Idle/src/components/navbar/Navbar.jsx
- frontend/Idle/src/pages/billPage.jsx
- close #146 
+++++ container에 데이터를 어떤 식으로 줄 지 몰라서 일단 동작 확인을 위해 본 코드는 주석 처리, 테스트 용 코드 작성+++++
> [FE] 견적서 페이지 옵션 박스 & 컨테이너

- backend/src/main/resources/data.sql
> [BE] data.sql 수정

- backend/src/test/java/com/autoever/idle/domain/function/FunctionRepositoryImplTest.java
- backend/src/test/java/com/autoever/idle/domain/myTrim/MyTrimControllerTest.java
- backend/src/test/java/com/autoever/idle/domain/myTrim/MyTrimServiceTest.java
- backend/src/test/resources/application.yml
> [BE] 내게 맞는 트림 찾기 API Test 수정

- backend/src/main/java/com/autoever/idle/domain/function/FunctionRepository.java
- backend/src/main/java/com/autoever/idle/domain/function/FunctionRepositoryImpl.java
- backend/src/main/java/com/autoever/idle/domain/myTrim/MyTrimController.java
- backend/src/main/java/com/autoever/idle/domain/myTrim/MyTrimService.java
- backend/src/main/java/com/autoever/idle/domain/myTrim/dto/MyTrimDto.java
- backend/src/main/java/com/autoever/idle/domain/myTrim/dto/MyTrimResDto.java
- backend/src/main/java/com/autoever/idle/global/exception/ErrorCode.java
- backend/src/main/java/com/autoever/idle/global/exception/GlobalExceptionHandler.java
- backend/src/main/java/com/autoever/idle/global/exception/custom/InvalidFunctionException.java
- backend/src/main/java/com/autoever/idle/global/exception/custom/InvalidMyTrimFunctionException.java
- backend/src/main/resources/data.sql
- backend/src/test/java/com/autoever/idle/domain/function/FunctionRepositoryImplTest.java
- backend/src/test/java/com/autoever/idle/domain/myTrim/MyTrimControllerTest.java
- backend/src/test/java/com/autoever/idle/domain/myTrim/MyTrimServiceTest.java
- backend/src/test/resources/application.yml
> [BE] 내게 맞는 트림 찾기 선택지 필터링 API 

- backend/src/test/java/com/autoever/idle/domain/detailModel/DetailModelControllerTest.java
- backend/src/test/java/com/autoever/idle/domain/detailModel/DetailModelServiceTest.java
> [BE] 세부 모델 통합 테스트 -> 유닛 테스트로 변경

- frontend/Idle/src/components/common/boxs/NormalTrimBox.jsx
- frontend/Idle/src/components/navbar/NavbarBox.jsx
- frontend/Idle/src/components/trimDetailModal/TrimDetailModal.jsx
- frontend/Idle/src/pages/billPage.jsx
- close #150 
- 페이지 전환 애니메이션을 하고 싶었지만 디자인상 별로 이쁘지 않아 추후 논의가 필요해보임
따라서 브렌치는 머지후 삭제하나 이슈는 남겨놓을 예정
- 지원하는 라이브러리는 많지만 바닐라로 짜는 것은 난이도 있어보임
> [FE] 모달 창 애니메이션 추가

- backend/src/main/java/com/autoever/idle/domain/function/TrimFunctionRepository.java
- backend/src/main/java/com/autoever/idle/domain/function/TrimFunctionRepositoryImpl.java
- backend/src/main/java/com/autoever/idle/domain/function/dto/FunctionIdDto.java
- backend/src/main/java/com/autoever/idle/domain/myTrim/MyTrimController.java
- backend/src/main/java/com/autoever/idle/domain/myTrim/MyTrimService.java
- backend/src/test/java/com/autoever/idle/domain/myTrim/MyTrimControllerTest.java
- backend/src/test/java/com/autoever/idle/domain/myTrim/MyTrimServiceTest.java
> [BE] 내게 맞는 트림 찾기 post로 변경

- backend/src/main/java/com/autoever/idle/global/config/WebConfig.java
> [Be] Cross Origin Resource Sharing 문제 해결

- .github/workflows/idle_workflow.yml
- backend/Dockerfile
- backend/build.gradle
- backend/src/main/java/com/autoever/idle/domain/bill/BillController.java
- backend/src/main/java/com/autoever/idle/domain/bill/dto/BillRequestDto.java
- backend/src/main/java/com/autoever/idle/domain/detailModel/DetailModelController.java
- backend/src/main/java/com/autoever/idle/domain/detailModel/dto/TrimIdRequest.java
- backend/src/main/java/com/autoever/idle/domain/function/FunctionController.java
- backend/src/test/java/com/autoever/idle/domain/detailModel/DetailModelControllerTest.java
- backend/src/test/java/com/autoever/idle/domain/function/FunctionControllerTest.java
> [BE] RequestBody -> QueryString으로 요청 변경

- backend/src/main/java/com/autoever/idle/domain/detailModel/bodyType/BodyTypeRepositoryImpl.java
- backend/src/main/java/com/autoever/idle/domain/detailModel/drivingMethod/DrivingMethodRepositoryImpl.java
- backend/src/main/java/com/autoever/idle/domain/detailModel/engine/EngineRepositoryImpl.java
- backend/src/test/java/com/autoever/idle/domain/detailModel/engine/EngineRepositoryImplTest.java
> [BE] 세부모델 각 목록 가격 오름차순으로 정렬되도록 수정

- backend/src/main/java/com/autoever/idle/domain/bill/BillController.java
- backend/src/main/java/com/autoever/idle/domain/bill/dto/BillRequestDto.java
- backend/src/test/java/com/autoever/idle/domain/bill/BillControllerTest.java
> [BE] 최종 견적서 API GET -> POST 요청으로 변경

- frontend/Idle/src/components/common/modals/OptionModal.jsx
- frontend/Idle/src/components/findTrim/FindTrimContent.jsx
- frontend/Idle/src/components/findTrim/Modal.jsx
- frontend/Idle/src/components/findTrim/OptionBox.jsx
- frontend/Idle/src/components/findTrim/TrimBox.jsx
- frontend/Idle/src/components/findTrim/TrimBoxOptionStatus.jsx
- frontend/Idle/src/utils/api.jsx
- frontend/Idle/src/utils/constants.jsx
- frontend/Idle/src/utils/reducer.jsx
- frontend/Idle/vite.config.js
- close #171
- 무슨 이유로 어떻게 코드를 변경했는지
- 어떤 부분에 리뷰어가 집중해야 하는지
- 개발하면서 어떤 점이 궁금했는지
> [FE] 내게맞는 트림찾기 API연결 

- backend/src/main/java/com/autoever/idle/domain/carMaster/CarMasterController.java
- backend/src/main/java/com/autoever/idle/domain/carMaster/CarMasterRepository.java
- backend/src/main/java/com/autoever/idle/domain/carMaster/CarMasterRepositoryImpl.java
- backend/src/main/java/com/autoever/idle/domain/carMaster/CarMasterService.java
- backend/src/main/java/com/autoever/idle/domain/carMaster/dto/CarMasterDto.java
- backend/src/test/java/com/autoever/idle/domain/carMaster/CarMasterControllerTest.java
- backend/src/test/java/com/autoever/idle/domain/carMaster/CarMasterRepositoryImplTest.java
- backend/src/test/java/com/autoever/idle/domain/carMaster/CarMasterServiceTest.java
- backend/src/test/resources/application.yml
> [BE] 카마스터 찾기 API 구현

- frontend/Idle/src/components/common/modals/OptionModal.jsx
- frontend/Idle/src/components/findTrim/FindTrimContent.jsx
- frontend/Idle/src/components/findTrim/Modal.jsx
- frontend/Idle/src/components/findTrim/OptionAlert.jsx
- frontend/Idle/src/components/findTrim/OptionBoxContainer.jsx
- frontend/Idle/src/components/findTrim/TrimBox.jsx
- frontend/Idle/src/utils/actionType.jsx
- frontend/Idle/src/utils/api.jsx
- frontend/Idle/src/utils/constants.jsx
- frontend/Idle/src/utils/reducer.jsx
- close #171
전역객체 차 dispatch와 내게맞는 트림찾기의 상태의 dispatch를 신경쓰며 작업하였습니다.
> [FE] 내게맞는 트림찾기 API연결

- backend/src/main/java/com/autoever/idle/global/config/WebConfig.java
> [BE] CORS 경로 추가

- frontend/Idle/src/components/colorSelection/InnerColorBoxContainer.jsx
- frontend/Idle/src/components/colorSelection/OutsideColorBoxContainer.jsx
- frontend/Idle/src/components/common/boxs/NormalTrimBox.jsx
- frontend/Idle/src/components/common/content/InnerColorContent.jsx
- frontend/Idle/src/pages/colorPage.jsx
- frontend/Idle/src/utils/constants.jsx
- frontend/Idle/src/utils/globalCar.jsx
- close #182 
- 필터를 전역차 객체에 디폴트 값이 들어간 상태에서 돌렸어야하는데 순서를 잘못해서 고생했다.
> [FE] 색상 페이지 api 연결 완료

- frontend/Idle/src/components/BillMain/DillerBox.jsx
- frontend/Idle/src/components/BillMain/DillerBoxContainer.jsx
- frontend/Idle/src/components/BillMain/Map.jsx
- frontend/Idle/src/components/BillMain/MapModal.jsx
- frontend/Idle/src/pages/detailModelPage.jsx
- frontend/Idle/src/utils/constants.jsx
> [Fe] 카마스터 api 연결

- frontend/Idle/src/components/defaultOption/DetailOptionModal.jsx
- frontend/Idle/src/components/defaultOption/ItemBox.jsx
- frontend/Idle/src/components/defaultOption/Modal.jsx
- frontend/Idle/src/components/defaultOption/PaginationButton.jsx
- frontend/Idle/src/pages/optionPage.jsx
- frontend/Idle/src/utils/constants.jsx
- close #212
상세보기떄문에 z-index를 조절했습니다.
설명에 대해  고정height를 설정하였습니다.
> [FE] ‘기본 옵션 페이지’ 호출 API 

- backend/src/main/java/com/autoever/idle/domain/bill/BillService.java
- backend/src/main/java/com/autoever/idle/domain/bill/dto/BillRequestDto.java
- backend/src/main/java/com/autoever/idle/domain/bill/dto/BillResponseDto.java
- backend/src/main/java/com/autoever/idle/domain/category/functionCategory/FunctionCategoryRepository.java
- backend/src/main/java/com/autoever/idle/domain/category/functionCategory/dto/DefaultFunctionCategoryResDto.java
- backend/src/main/java/com/autoever/idle/domain/function/FunctionRepository.java
- backend/src/main/java/com/autoever/idle/domain/function/FunctionRepositoryImpl.java
- backend/src/main/java/com/autoever/idle/domain/option/OptionRepository.java
- backend/src/main/java/com/autoever/idle/domain/option/OptionRepositoryImpl.java
- backend/src/main/java/com/autoever/idle/domain/option/dto/SelectedOptionDto.java
- backend/src/test/java/com/autoever/idle/domain/bill/BillControllerTest.java
- backend/src/test/java/com/autoever/idle/domain/bill/BillServiceTest.java
- backend/src/test/java/com/autoever/idle/domain/function/FunctionRepositoryImplTest.java
- backend/src/test/java/com/autoever/idle/domain/option/OptionRepositoryImplTest.java
> [BE] 견적서 API 반환 정보 수정

- frontend/Idle/src/components/BillMain/BillDetail.jsx
- frontend/Idle/src/components/BillMain/BillOptionBox.jsx
- frontend/Idle/src/components/BillMain/BillOptionContainer.jsx
- frontend/Idle/src/components/common/boxs/NormalTrimBox.jsx
- frontend/Idle/src/components/findTrim/Modal.jsx
- frontend/Idle/src/pages/billPage.jsx
- frontend/Idle/src/utils/reducer.jsx
- close #214 
- 아직 옵션이 없을때의 api가 예외처리가 되어있지 않아 오류 발생
- 색상이 하얀색일때 안보니는 글씨에 그림자 효과 추가
> [feat] 최종 견적서 페이지 api 연결

- frontend/Idle/src/components/BillMain/BillOptionContainer.jsx
- frontend/Idle/src/components/common/modals/WarningModal.jsx
- frontend/Idle/src/components/navbar/NavbarBox.jsx
- frontend/Idle/src/components/navbar/index.jsx
- frontend/Idle/src/pages/billPage.jsx
- close #issue_number
- 모달의 오픈 상태를 navBox에서 선언 했더니 여러개의 박스에서 여러개의 상태를 공존해서 가지게 되니 모달이 꺼지지 않는 버그가 발생했는데 이를 감싸는 컨테이너로 이동시키니 해결되었다.
> [FE] 모든 옵션들을 선택했을 때 견적서 이동이 가능하도록 변경

- backend/src/main/java/com/autoever/idle/domain/bill/BillService.java
- backend/src/main/java/com/autoever/idle/domain/bill/dto/BillResponseDto.java
- backend/src/main/java/com/autoever/idle/domain/trim/TrimRepository.java
- backend/src/main/java/com/autoever/idle/domain/trim/TrimRepositoryImpl.java
- backend/src/main/java/com/autoever/idle/domain/trim/dto/TrimDescriptionDto.java
- backend/src/test/java/com/autoever/idle/domain/bill/BillControllerTest.java
- backend/src/test/java/com/autoever/idle/domain/bill/BillServiceTest.java
- backend/src/test/java/com/autoever/idle/domain/trim/TrimRepositoryTest.java
> [BE] 견적서 정보에 트림 설명 추가

- backend/src/main/java/com/autoever/idle/domain/option/OptionRepositoryImpl.java
- backend/src/main/java/com/autoever/idle/domain/option/OptionService.java
- backend/src/test/java/com/autoever/idle/domain/option/OptionServiceTest.java
> [BE] 추가 옵션 목록이 빈 배열일 때 쿼리 동적으로 수정

- backend/src/main/java/com/autoever/idle/domain/carMaster/CarMasterRepositoryImpl.java
- backend/src/main/java/com/autoever/idle/domain/carMaster/dto/CarMasterDto.java
- backend/src/test/java/com/autoever/idle/domain/carMaster/CarMasterControllerTest.java
- backend/src/test/java/com/autoever/idle/domain/carMaster/CarMasterServiceTest.java
> [BE] 카마스터 찾기 시 카마스터의 주소, marker이미지 정보 반환 추가

- frontend/Idle/src/components/common/boxs/DetailModelBox.jsx
- frontend/Idle/src/components/common/boxs/OptionBox.jsx
- frontend/Idle/src/pages/optionPage.jsx
- frontend/Idle/src/utils/globalCar.jsx
- close #229
useEffect를 나눠서, 잘 적용되도록했습니다.
optionId도 추가되도록했습니다.
> [FE] 추가옵션 페이지 API적용

- frontend/Idle/src/components/common/boxs/OptionBox.jsx
- frontend/Idle/src/pages/billPage.jsx
- frontend/Idle/src/pages/optionPage.jsx
> [FE] 툴팁 적용

- .idea/.gitignore
- .idea/A5-Idle.iml
- .idea/compiler.xml
- .idea/gradle.xml
- .idea/inspectionProfiles/Project_Default.xml
- .idea/jarRepositories.xml
- .idea/misc.xml
- .idea/modules.xml
- .idea/vcs.xml
- backend/settings.gradle
- backend/src/main/java/com/autoever/idle/IdleApplication.java
- backend/src/main/java/com/autoever/idle/domain/trim/service/TrimService.java
> [fix] be-main 살리기 위한 커밋

- frontend/Idle/package-lock.json
- frontend/Idle/package.json
- frontend/Idle/src/pages/billPage.jsx
> [Fe] 공유하기 버튼 클릭 시 pdf 다운 

- backend/src/main/java/com/autoever/idle/domain/carType/repository/CarTypeRepository.java
- backend/src/main/java/com/autoever/idle/domain/carType/repository/CarTypeRepositoryImpl.java
- backend/src/main/java/com/autoever/idle/domain/exteriorColor/dto/ExteriorImgUrlDto.java
- backend/src/main/java/com/autoever/idle/domain/exteriorColor/dto/TrimThumbnailColorResponse.java
- backend/src/main/java/com/autoever/idle/domain/exteriorColor/repository/ExteriorColorRepository.java
- backend/src/main/java/com/autoever/idle/domain/exteriorColor/repository/ExteriorColorRepositoryImpl.java
- backend/src/main/java/com/autoever/idle/domain/interiorColor/dto/InteriorImgUrlDto.java
- backend/src/main/java/com/autoever/idle/domain/interiorColor/repository/InteriorColorRepository.java
- backend/src/main/java/com/autoever/idle/domain/interiorColor/repository/InteriorColorRepositoryImpl.java
- backend/src/main/java/com/autoever/idle/domain/trim/dto/TrimSelectionResponse.java
- backend/src/main/java/com/autoever/idle/domain/trim/service/TrimService.java
- backend/src/test/java/com/autoever/idle/domain/carType/CarTypeRepositoryTest.java
- backend/src/test/java/com/autoever/idle/domain/exteriorColor/ExteriorColorRepositoryTest.java
- backend/src/test/java/com/autoever/idle/domain/interiorColor/InteriorColorRepositoryImplTest.java
- backend/src/test/java/com/autoever/idle/domain/trim/TrimControllerTest.java
- backend/src/test/java/com/autoever/idle/domain/trim/TrimServiceTest.java
> [BE] 트림 조회 시 외장, 내장 색상 정보 반환

- backend/src/main/java/com/autoever/idle/domain/carMaster/controller/CarMasterController.java
- backend/src/main/java/com/autoever/idle/domain/carMaster/repository/CarMasterRepositoryImpl.java
- backend/src/main/java/com/autoever/idle/domain/carMaster/service/CarMasterService.java
> [BE] 카마스터 찾기 리팩토링

- backend/src/main/resources/data.sql
- backend/src/main/resources/schema.sql
- backend/src/test/resources/h2Schema.sql
> [BE] CAR_TYPE, CAR_CATEGORY 테이블 수정 및 추가

- frontend/Idle/src/components/navbar/NavbarBox.jsx
- frontend/Idle/src/components/navbar/index.jsx
- frontend/Idle/src/pages/colorPage.jsx
- frontend/Idle/src/utils/constants.jsx
> [FE] 트림, 엔진 선택 후에만 옵션 페이지 이동 가능

- frontend/Idle/src/components/BillMain/DillerBox.jsx
- frontend/Idle/src/components/common/boxs/DetailModelBox.jsx
- frontend/Idle/src/components/common/modals/RemoveOptionModal.jsx
- frontend/Idle/src/components/defaultOption/DetailOptionModal.jsx
- frontend/Idle/src/pages/detailModelPage.jsx
> [FE] 옵션 변경 경고 모달 연결

- frontend/Idle/src/components/common/boxs/NormalTrimBox.jsx
- frontend/Idle/src/components/common/buttons/ModifyButton.jsx
- frontend/Idle/src/components/common/content/Car3D.jsx
- frontend/Idle/src/components/common/modals/WarningModal.jsx
- frontend/Idle/src/components/defaultOption/CloseButton.jsx
- frontend/Idle/src/components/defaultOption/DefaultOptionButton.jsx
- frontend/Idle/src/components/defaultOption/DetailOptionModal.jsx
- frontend/Idle/src/components/defaultOption/ItemBox.jsx
- frontend/Idle/src/components/defaultOption/Modal.jsx
- frontend/Idle/src/components/findTrim/FindTrimButton.jsx
- frontend/Idle/src/components/trimDetailModal/OptionDropDown.jsx
- frontend/Idle/src/components/trimDetailModal/TrimDetailModal.jsx
- frontend/Idle/src/components/trimMain/ExteriorBoxContainer.jsx
- frontend/Idle/src/components/trimMain/InteriorBoxContainer.jsx
- frontend/Idle/src/components/trimMain/index.jsx
- frontend/Idle/src/pages/billPage.jsx
- frontend/Idle/src/pages/optionPage.jsx
- frontend/Idle/src/pages/trimPage.jsx
- close #283 
- close #284 
- close #285 
- 색상 박스 Hover 시에 차량 색상 이미지도 바꾸고 싶었지만 데이터도 없고 구현 난이도도 구조때문에 좀 힘들어 보여서 추후 예정
색상 박스 구현
기본 옵션 박스 디자인 수정
&emsp;&emsp;  &emsp;&emsp; BEFORE   &emsp; &emsp; &emsp;&emsp;&emsp; &emsp;&emsp; &emsp; &emsp;&emsp;AFTER
툴팁 화살표 애니메이션 추가
> [FE] 트림 선택 페이지 외장, 내장 색상 박스 구현

- frontend/Idle/src/components/carSelection/CarSelectionBox.jsx
- frontend/Idle/src/components/carSelection/CarSelectionContainer.jsx
- frontend/Idle/src/pages/mainPage.jsx
- frontend/Idle/src/pages/selectCarPage.jsx
- frontend/Idle/src/utils/constants.jsx
- frontend/Idle/src/utils/router.jsx
> [FE] 차량 선택 페이지

- backend/src/main/resources/data.sql
> [BE] option_status테이블에 데이터 추가

- frontend/Idle/src/components/common/loading/Loading.jsx
- frontend/Idle/src/pages/trimPage.jsx
- frontend/Idle/src/utils/router.jsx
- close #306 
- router에서 lazyLoading과 함께 suspense를 적용하였다.
> [FE] 로딩 컴포넌트 구현

- frontend/Idle/src/components/optionMain/Functions.jsx
- frontend/Idle/src/components/optionMain/OptionContent.jsx
> [Fe] 옵션 페이지 크기 조절

- backend/src/main/java/com/autoever/idle/domain/carMaster/repository/CarMasterRepositoryImpl.java
- backend/src/main/java/com/autoever/idle/domain/carType/repository/CarTypeRepositoryImpl.java
- backend/src/main/java/com/autoever/idle/domain/category/carCategory/repository/CarCategoryRepositoryImpl.java
- backend/src/main/java/com/autoever/idle/domain/category/functionCategory/dto/DefaultFunctionCategoryResponse.java
- backend/src/main/java/com/autoever/idle/domain/category/functionCategory/dto/FunctionCategoryDto.java
- backend/src/main/java/com/autoever/idle/domain/category/functionCategory/repository/FunctionCategoryRepositoryImpl.java
- backend/src/main/java/com/autoever/idle/domain/detailModel/bodyType/repository/BodyTypeRepositoryImpl.java
- backend/src/main/java/com/autoever/idle/domain/detailModel/drivingMethod/repository/DrivingMethodRepositoryImpl.java
- backend/src/main/java/com/autoever/idle/domain/detailModel/engine/repository/EngineRepositoryImpl.java
- backend/src/main/java/com/autoever/idle/domain/exteriorColor/dto/CarExteriorImgDto.java
- backend/src/main/java/com/autoever/idle/domain/exteriorColor/dto/ExteriorColorDto.java
- backend/src/main/java/com/autoever/idle/domain/exteriorColor/dto/ExteriorImgUrlDto.java
- backend/src/main/java/com/autoever/idle/domain/exteriorColor/repository/ExteriorColorRepositoryImpl.java
- backend/src/main/java/com/autoever/idle/domain/function/dto/DefaultFunctionNameResponse.java
- backend/src/main/java/com/autoever/idle/domain/function/repository/FunctionRepositoryImpl.java
- backend/src/main/java/com/autoever/idle/domain/interiorColor/repository/InteriorColorRepositoryImpl.java
- backend/src/main/java/com/autoever/idle/domain/option/repository/OptionRepositoryImpl.java
- backend/src/main/java/com/autoever/idle/domain/trim/dto/TrimDto.java
- backend/src/main/java/com/autoever/idle/domain/trim/dto/TrimSelectionResponse.java
- backend/src/main/java/com/autoever/idle/domain/trim/repository/TrimRepositoryImpl.java
- backend/src/main/java/com/autoever/idle/domain/trim/service/TrimService.java
- backend/src/main/java/com/autoever/idle/domain/trimThumbnailFunction/dto/TrimThumbnailFunctionResponse.java
- backend/src/main/java/com/autoever/idle/domain/trimThumbnailFunction/repository/TrimThumbnailFunctionRepositoryImpl.java
- backend/src/test/java/com/autoever/idle/domain/trim/TrimControllerTest.java
> [BE] 트림 선택, 외장 색상 선택, 내장 색상 선택 API 리팩토링

- frontend/Idle/src/components/BillMain/MapModal.jsx
- frontend/Idle/src/components/common/boxs/NormalTrimBox.jsx
- frontend/Idle/src/components/defaultOption/Modal.jsx
- frontend/Idle/src/components/findTrim/FindTrimContent.jsx
- frontend/Idle/src/components/findTrim/TrimBox.jsx
- frontend/Idle/src/components/optionMain/Functions.jsx
- frontend/Idle/src/pages/billPage.jsx
- frontend/Idle/src/pages/colorPage.jsx
- frontend/Idle/src/pages/detailModelPage.jsx
- frontend/Idle/src/pages/optionPage.jsx
- frontend/Idle/src/pages/trimPage.jsx
- frontend/Idle/src/utils/api.jsx
- close #321
getAPI가 상황마다 다르므로 이름을 수정했습니다.
> [FE] 추가옵션 페이지 POST->GET으로

- backend/src/main/java/com/autoever/idle/domain/bill/controller/BillController.java
- backend/src/main/java/com/autoever/idle/domain/detailModel/dto/EngineResponse.java
- backend/src/main/java/com/autoever/idle/domain/detailModel/engine/repository/EngineRepositoryImpl.java
- backend/src/main/java/com/autoever/idle/domain/function/controller/FunctionController.java
- backend/src/main/java/com/autoever/idle/domain/function/service/FunctionService.java
- backend/src/main/java/com/autoever/idle/domain/option/service/OptionService.java
> [BE] 세부모델, 견적서 API 리팩토링

- backend/src/main/java/com/autoever/idle/domain/myTrim/controller/MyTrimController.java
- backend/src/main/java/com/autoever/idle/domain/myTrim/dto/MyTrimSubmitRequest.java
- backend/src/main/java/com/autoever/idle/domain/myTrim/service/MyTrimService.java
- backend/src/test/java/com/autoever/idle/domain/myTrim/MyTrimControllerTest.java
- backend/src/test/java/com/autoever/idle/domain/myTrim/MyTrimServiceTest.java
> [BE] 내게 맞는 트림 찾기 API POST -> GET 으로 수정

- backend/src/main/java/com/autoever/idle/domain/exteriorColor/service/ExteriorColorService.java
> [BE] 외장 색상 정렬 로직 리팩토링

- frontend/Idle/src/pages/selectCarPage.jsx
- frontend/Idle/src/utils/constants.jsx
> [FE] 차량 선택 api 연결

- backend/src/main/java/com/autoever/idle/IdleApplication.java
- backend/src/main/java/com/autoever/idle/domain/bill/controller/BillController.java
- backend/src/main/java/com/autoever/idle/domain/myTrim/controller/MyTrimController.java
- backend/src/main/java/com/autoever/idle/domain/myTrim/dto/MyTrimSubmitRequest.java
- backend/src/main/java/com/autoever/idle/domain/myTrim/service/MyTrimService.java
- backend/src/main/java/com/autoever/idle/domain/option/controller/OptionController.java
> [BE] 내게 맞는 트림 찾기 선택지 필터링 캐싱

- backend/src/main/java/com/autoever/idle/domain/exteriorColor/dto/ExteriorColorResponse.java
- backend/src/main/java/com/autoever/idle/domain/exteriorColor/service/ExteriorColorService.java
- backend/src/main/java/com/autoever/idle/domain/interiorColor/controller/InteriorColorController.java
- backend/src/main/java/com/autoever/idle/domain/interiorColor/dto/InteriorColorResponse.java
- backend/src/main/java/com/autoever/idle/domain/interiorColor/dto/InteriorColorsImgUrlResponse.java
- backend/src/main/java/com/autoever/idle/domain/interiorColor/repository/InteriorColorRepository.java
- backend/src/main/java/com/autoever/idle/domain/interiorColor/repository/InteriorColorRepositoryImpl.java
- backend/src/main/java/com/autoever/idle/domain/interiorColor/service/InteriorColorService.java
- backend/src/test/java/com/autoever/idle/domain/interiorColor/InteriorColorControllerTest.java
- backend/src/test/java/com/autoever/idle/domain/interiorColor/InteriorColorRepositoryImplTest.java
- backend/src/test/java/com/autoever/idle/domain/interiorColor/InteriorColorServiceTest.java
> [BE] 내장 색상 이미지 전체 조회 API

- backend/src/main/java/com/autoever/idle/domain/trim/controller/TrimController.java
> [BE] 트림 조회 캐싱 처리

- frontend/Idle/src/components/colorPage/colorMain/ColorTabContainer.jsx
- frontend/Idle/src/components/colorPage/colorSub/ColorConfirmContainer.jsx
- frontend/Idle/src/components/detailModelPage/detailModelMain/DetailModelMain.jsx
- frontend/Idle/src/components/detailModelPage/detailModelMain/DetailModelTabContainer.jsx
- frontend/Idle/src/components/detailModelPage/detailModelSub/DetailModelBoxContainer.jsx
- frontend/Idle/src/components/detailModelPage/detailModelSub/DetailModelConfirmContainer.jsx
- frontend/Idle/src/components/optionPage/optionMain/OptionMain.jsx
- frontend/Idle/src/components/optionPage/optionMain/OptionTabContainer.jsx
- frontend/Idle/src/components/optionPage/optionSub/OptionBoxContainer.jsx
- frontend/Idle/src/components/optionPage/optionSub/OptionConfirmContainer.jsx
- frontend/Idle/src/components/trimPage/trimSub/TrimConfirmContainer.jsx
- frontend/Idle/src/pages/colorPage.jsx
- frontend/Idle/src/pages/detailModelPage.jsx
- frontend/Idle/src/pages/optionPage.jsx
- frontend/Idle/src/pages/trimPage.jsx
> [FE] 페이지 컴포넌트 분리

- backend/src/main/java/com/autoever/idle/domain/category/functionCategory/repository/FunctionCategoryRepositoryImpl.java
> [BE] 견적서 dto, 쿼리 매칭 문제 해결

- frontend/Idle/src/components/optionPage/optionMain/OptionFunctions.jsx
- frontend/Idle/src/components/trimPage/findTrim/findTrimMain/TrimBox.jsx
- frontend/Idle/src/components/trimPage/findTrim/findTrimMain/TrimBoxContainer.jsx
- frontend/Idle/src/pages/billPage.jsx
- frontend/Idle/src/pages/carSelectionPage.jsx
- close #issue_number
``` css
@media print {
& * {
opacity: 1 !important;
transform: none !important;
}
}
```
로 수정
> [FE] 4Week-1 fe-dev to main Merge

- frontend/Idle/src/components/common/buttons/AddButton.jsx
- frontend/Idle/src/components/common/buttons/ConfusingButton.jsx
- frontend/Idle/src/components/trimPage/findTrim/findTrimSub/OptionBox.jsx
- frontend/Idle/src/pages/mainPage.jsx
> [Fe] fe-dev to main merge
